data.gear_stats = {
    ["Adhemar Bonnet"]      = { haste = 8, dual_wield = 0 },
    ["Adhemar Gamashes"]    = { haste = 4, dual_wield = 0 },
    ["Adhemar Jacket"]      = { haste = 4, dual_wield = 5 },
    ["Adhemar Wristbands"]  = { haste = 5, dual_wield = 0 },
    ["Amalric Coif"]        = { haste = 6, dual_wield = 0 },
    ["Amalric Doublet"]     = { haste = 3, dual_wield = 0 },
    ["Amalric Gages"]       = { haste = 3, dual_wield = 0 },
    ["Amalric Nails"]       = { haste = 3, dual_wield = 0 },
    ["Amalric Slops"]       = { haste = 5, dual_wield = 0 },
    ["Amm Greaves"]         = { haste = 3, dual_wield = 0 },
    ["Befouled Crown"]      = { haste = 6, dual_wield = 0 },
    ["Cab. Breeches"]       = { haste = 5, dual_wield = 0 },
    ["Cab. Surcoat +1"]     = { haste = 3, dual_wield = 0 },
    ["Carmine Mask"]        = { haste = 8, dual_wield = 0 },
    ["Chev. Cuisses +1"]    = { haste = 5, dual_wield = 0 },
    ["Chironic Doublet"]    = { haste = 3, dual_wield = 0 },
    ["Chironic Hose "]      = { haste = 5, dual_wield = 0 },
    ["Dampening Tam"]       = { haste = 7, dual_wield = 0 },
    ["Doyen Pants"]         = { haste = 5, dual_wield = 0 },
    ["Dynasty Mitts"]       = { haste = 3, dual_wield = 0 },
    ["Ebers Bliaud +1"]     = { haste = 3, dual_wield = 0 },
    ["Ebers Cap +1"]        = { haste = 6, dual_wield = 0 },
    ["Ebers Duckbills +1"]  = { haste = 3, dual_wield = 0 },
    ["Ebers Mitts +1"]      = { haste = 3, dual_wield = 0 },
    ["Ebers Pant. +1"]      = { haste = 5, dual_wield = 0 },
    ["Eschite Gauntlets"]   = { haste = 4, dual_wield = 0 },
    ["Fanatic Gloves"]      = { haste = 3, dual_wield = 0 },
    ["Foppish Tunica"]      = { haste = 4, dual_wield = 0 },
    ["Founders' Corona"]    = { haste = 7, dual_wield = 0 },
    ["Frenzy Sallet"]       = { haste = 4, dual_wield = 0 },
    ["Gende. Galoshes"]     = { haste = 3, dual_wield = 0 },
    ["Gyve Doublet"]        = { haste = 3, dual_wield = 0 },
    ["Gyve Trousers"]       = { haste = 5, dual_wield = 0 },
    ["Hashishin Mintan"]    = { haste = 3, dual_wield = 0 },
    ["Helios Band"]         = { haste = 6, dual_wield = 0 },
    ["Helios Boots"]        = { haste = 3, dual_wield = 0 },
    ["Helios Gloves"]       = { haste = 3, dual_wield = 0 },
    ["Herculean Boots"]     = { haste = 4, dual_wield = 0 },
    ["Herculean Helm"]      = { haste = 8, dual_wield = 0 },
    ["Herculean Trousers"]  = { haste = 6, dual_wield = 0 },
    ["Herculean Vest"]      = { haste = 4, dual_wield = 0 },
    ["Horos Casaque +1"]    = { haste = 4, dual_wield = 0 },
    ["Horos Tiara +1"]      = { haste = 8, dual_wield = 0 },
    ["Horos Tights +1"]     = { haste = 6, dual_wield = 0 },
    ["Hygieia Clogs"]       = { haste = 3, dual_wield = 0 },
    ["Inyan. Dastanas +1"]  = { haste = 4, dual_wield = 0 },
    ["Inyanga Jubbah +1"]   = { haste = 2, dual_wield = 0 },
    ["Inyanga Tiara +1"]    = { haste = 4, dual_wield = 0 },
    ["Jhakri Robe +1"]      = { haste = 1, dual_wield = 0 },
    ["Jumalik Mail"]        = { haste = 3, dual_wield = 0 },
    ["Kaykaus Bliaut"]      = { haste = 3, dual_wield = 0 },
    ["Kaykaus Cuffs"]       = { haste = 3, dual_wield = 0 },
    ["Lengo Pants"]         = { haste = 5, dual_wield = 0 },
    ["Leyline Gloves"]      = { haste = 5, dual_wield = 0 },
    ["Lilitu Headpiece"]    = { haste = 7, dual_wield = 0 },
    ["Limbo Trousers"]      = { haste = 6, dual_wield = 0 },
    ["Luhlaza Charuqs +1"]  = { haste = 4, dual_wield = 0 },
    ["Lustratio Leggings"]  = { haste = -5, dual_wield = 0 },
    ["Lustratio Subligar"]  = { haste = -13, dual_wield = 0 },
    ["Macu. Bangles +1"]    = { haste = 5, dual_wield = 0 },
    ["Maculele Tiara +1"]   = { haste = 8, dual_wield = 0 },
    ["Macu. Toeshoes +1"]   = { haste = 5, dual_wield = 0 },
    ["Maxixi Casaque +1"]   = { haste = 4, dual_wield = 0 },
    ["Maxixi Shoes +1"]     = { haste = 4, dual_wield = 0 },
    ["Maxixi Tiara"]        = { haste = 7, dual_wield = 0 },
    ["Meg. Chausses +1"]    = { haste = 4, dual_wield = 0 },
    ["Meg. Cuirie +1"]      = { haste = 2, dual_wield = 0 },
    ["Meg. Gloves +1"]      = { haste = 4, dual_wield = 0 },
    ["Meg. Jam. +1"]        = { haste = 2, dual_wield = 0 },
    ["Meghanada Visor +1"]  = { haste = 4, dual_wield = 0 },
    ["Mekosu. Harness"]     = { haste = 4, dual_wield = 0 },
    ["Merlinic Crackows"]   = { haste = 3, dual_wield = 0 },
    ["Merlinic Dastanas"]   = { haste = 3, dual_wield = 0 },
    ["Merlinic Hood"]       = { haste = 6, dual_wield = 0 },
    ["Merlinic Jubbah"]     = { haste = 3, dual_wield = 0 },
    ["Merlinic Shalwar"]    = { haste = 5, dual_wield = 0 },
    ["Odyssean Cuisses"]    = { haste = 5, dual_wield = 0 },
    ["Odyssean Gauntlets"]  = { haste = 4, dual_wield = 0 },
    ["Odyssean Greaves"]    = { haste = 3, dual_wield = 0 },
    ["Odyssean Helm"]       = { haste = 7, dual_wield = 0 },
    ["Passion Jacket"]      = { haste = 3, dual_wield = 0 },
    ["Piety Briault +1"]    = { haste = 3, dual_wield = 0 },
    ["Piety Cap"]           = { haste = 5, dual_wield = 0 },
    ["Piety Duckbills +1"]  = { haste = 3, dual_wield = 0 },
    ["Piety Mitts"]         = { haste = 3, dual_wield = 0 },
    ["Piety Pantaln. +1"]   = { haste = 5, dual_wield = 0 },
    ["Pillager's Poulaines"]= { haste = 4, dual_wield = 0 },
    ["Plun. Armlets +1"]    = { haste = 5, dual_wield = 0 },
    ["Psycloth Manillas"]   = { haste = 3, dual_wield = 0 },
    ["Rawhide Mask"]        = { haste = 8, dual_wield = 0 },
    ["Rev. Coronet"]        = { haste = 6, dual_wield = 0 },
    ["Samnuha Coat"]        = { haste = 4, dual_wield = 0 },
    ["Samnuha Tights"]      = { haste = 6, dual_wield = 0 },
    ["Shango Robe"]         = { haste = 3, dual_wield = 0 },
    ["Skulk. Poulaines +1"] = { haste = 4, dual_wield = 0 },
    ["Souveran Cuirass"]    = { haste = 3, dual_wield = 0 },
    ["Souveran Diechlings"] = { haste = 5, dual_wield = 0 },
    ["Souv. Handschuhs"]    = { haste = 4, dual_wield = 0 },
    ["Souveran Schuhs"]     = { haste = 3, dual_wield = 0 },
    ["Sulev. Gauntlets +1"] = { haste = 3, dual_wield = 0 },
    ["Tartarus Platemail"]  = { haste = 3, dual_wield = 0 },
    ["Telchine Braconi"]    = { haste = 5, dual_wield = 0 },
    ["Telchine Cap"]        = { haste = 6, dual_wield = 0 },
    ["Telchine Chas."]      = { haste = 3, dual_wield = 0 },
    ["Telchine Gloves"]     = { haste = 3, dual_wield = 0 },
    ["Telchine Pigaches"]   = { haste = 3, dual_wield = 0 },
    ["Theo. Briault"]       = { haste = 2, dual_wield = 0 },
    ["Theo. Cap +1"]        = { haste = 6, dual_wield = 0 },
    ["Theo. Duckbills"]     = { haste = 3, dual_wield = 0 },
    ["Theo. Mitts +1"]      = { haste = 3, dual_wield = 0 },
    ["Theo. Pant. +1"]      = { haste = 5, dual_wield = 0 },
    ["Toetapper Mantle"]    = { haste = 0, dual_wield = 0 },
    ["Vanya Hood"]          = { haste = 6, dual_wield = 0 },
    ["Vanya Robe"]          = { haste = 3, dual_wield = 0 },
    ["Vatic Byrnie"]        = { haste = 3, dual_wield = 0 },
    ["Wicce Coat +1"]       = { haste = 3, dual_wield = 0 },
}
